/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import models.*;
import persistence.ApplicationDbContext;

/**
 *
 * @author jonbr
 */
public class OrderPanel extends javax.swing.JPanel implements IDbPanel<CustomerOrder> {

    private boolean isDirty = false;
    
    /**
     * Used to display a list of all customer orders
     */
    DefaultListModel<CustomerOrder> orderModel;
    
    /**
     * Used to display a list of all items on order for selected customer order
     */
    DefaultListModel<OrderItem> orderItemModel;
    
    private Customer selectedCustomer;
    private Address selectedAddress;
    private CustomerOrder selectedCustomerOrder;
    private OrderItem selectedOrderItem;
    
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        initializeCustomerModel();
    }

    /**
     * Populates the customer model with a list of customers from the database
     */
    private void initializeCustomerModel()
    {
        jcCustomerOption.removeAll();
        var customers = ApplicationDbContext.getInstance().customers.get("addresses");
        
        for(Customer customer : customers)
            jcCustomerOption.addItem(customer);
    }
    
    /**
     * Sets selectedCustomer to specified index from model
     * Updates address model to display customer's associated addresses
     * @param index 
     */
    private void selectCustomer(int index)
    {
        selectedCustomer = (Customer) jcCustomerOption.getSelectedItem();
        
        jcCustomerAddressOption.removeAll();
        
        for(Address address : selectedCustomer.getAddresses())
            jcCustomerAddressOption.addItem(address);
    }
    
    private void selectOrder(int index)
    {
        selectedCustomerOrder = orderModel.get(index);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcCustomerOption = new javax.swing.JComboBox<>();
        jcCustomerAddressOption = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnRemoveOrderItem = new javax.swing.JButton();
        btnSubmitOrder = new javax.swing.JButton();
        btnViewCustomerOrders = new javax.swing.JButton();

        jcCustomerOption.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcCustomerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCustomerOptionActionPerformed(evt);
            }
        });

        jcCustomerAddressOption.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcCustomerAddressOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCustomerAddressOptionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Customer:");

        jList1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        btnRemoveOrderItem.setBackground(new java.awt.Color(255, 51, 51));
        btnRemoveOrderItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnRemoveOrderItem.setText("Remove");
        btnRemoveOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderItemActionPerformed(evt);
            }
        });

        btnSubmitOrder.setBackground(new java.awt.Color(102, 255, 51));
        btnSubmitOrder.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSubmitOrder.setText("Submit");
        btnSubmitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOrderActionPerformed(evt);
            }
        });

        btnViewCustomerOrders.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnViewCustomerOrders.setText("View Customer Orders");
        btnViewCustomerOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcCustomerOption, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcCustomerAddressOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRemoveOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewCustomerOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcCustomerOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcCustomerAddressOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveOrderItem)
                    .addComponent(btnSubmitOrder)
                    .addComponent(btnViewCustomerOrders))
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveOrderItemActionPerformed

    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitOrderActionPerformed

    private void btnViewCustomerOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCustomerOrdersActionPerformed

    private void jcCustomerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCustomerOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCustomerOptionActionPerformed

    private void jcCustomerAddressOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCustomerAddressOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCustomerAddressOptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoveOrderItem;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JButton btnViewCustomerOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Address> jcCustomerAddressOption;
    private javax.swing.JComboBox<Customer> jcCustomerOption;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setDirty(boolean value) {
        isDirty = value;   
    }

    @Override
    public void onItemSelected(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void delete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void save() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ArrayList<CustomerOrder> getAllItems() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void resetItemData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
